Protocol v2
vostok/clusterconfig.client pull request #17
Opened 2022-01-27 02:34 UTC by anaym

2022-01-27 08:04 UTC, KungA commented on Vostok.ClusterConfig.Client/ClusterConfigClientSettings.cs
> +        public ProtocolVersion? ForcedProtocolVersion { get; set; } = null;
а где документация к этой настройке?

2022-01-27 08:07 UTC, KungA commented on Vostok.ClusterConfig.Client/ClusterConfigClient.cs
> +            var protocol = settings.ForcedProtocolVersion ?? DefaultProtocol;
как-то странно работает случай, когда не задана ForcedProtocolVersion

если я правильно понял, то мы в начале можем запросить всю зону V1, нам ответят, что recommended = V2 и мы снова всё перезапросим, что странно

уж проще было сообщить серверу supported version, и чтобы он нам ответил той, что посчитал более правильной

2022-01-27 11:23 UTC, KungA commented on Vostok.ClusterConfig.Client/ClusterConfigClient.cs
> +            var protocol = settings.ForcedProtocolVersion ?? DefaultProtocol;
вообще все эти костыли с переключением версии с обеих сторон выглядят излишне

уж проще всегда на клиенте выбирать версию, да и всё

2022-01-27 12:05 UTC, anaym commented on Vostok.ClusterConfig.Client/ClusterConfigClient.cs
> +            var protocol = settings.ForcedProtocolVersion ?? DefaultProtocol;
> если я правильно понял, то мы в начале можем запросить всю зону V1, нам ответят, что recommended = V2 и мы снова всё перезапросим, что странно

Мы не перезапросим новую версию до обновления зоны. В тот момент когда зона обновится - да, мы пришлём уже V2 целиком.

2022-01-27 12:06 UTC, anaym commented on Vostok.ClusterConfig.Client/ClusterConfigClient.cs
> +            var protocol = settings.ForcedProtocolVersion ?? DefaultProtocol;
> вообще все эти костыли с переключением версии с обеих сторон выглядят излишне
уж проще всегда на клиенте выбирать версию, да и всё
один фиг, если в ней баг, придется обновлять либу

Это возможность полечить баг оперативно, не дожидаясь обновления клиентов. Так же это позволит нам тестироваться на отдельных ветках, а не сразу на default

2022-01-27 12:49 UTC, KungA commented on Vostok.ClusterConfig.Client/Helpers/ApplyPatchHelper.cs
> +public static class ApplyPatchHelper
public?

2022-01-27 13:02 UTC, KungA requested changes

2022-01-27 13:10 UTC, KungA commented on Vostok.ClusterConfig.Client/Updaters/ClusterConfigHeaderNames.cs
> +        public const string ReplicaName = "X-Kontur-ClusterConfig-Replica";
не увидел, а это для чего заголовок?

2022-01-28 04:22 UTC, anaym commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            if (lastProtocol == null)
В том что если зона не менялась, то даже с foceFull тебе вернётся NotModified, а не Ok

2022-01-28 04:24 UTC, anaym commented on Vostok.ClusterConfig.Client/Updaters/ClusterConfigHeaderNames.cs
> +        public const string ReplicaName = "X-Kontur-ClusterConfig-Replica";
Это пока не нужно в восточном клиенте, но нужно для SloMeter - не захотел заводить два класса в двух разных проектах для хэдеров CC. Ну и метод получения информации о всех зонах (в котором хэдер этот используется) потом можно будет добавить и в восточный клиент

2022-01-28 04:25 UTC, anaym commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> -        private static Exception Empty200ResponseException()
Хз, меня крайне раздражают методы вида LogBlaBlaBla или BlaBlaBlaException. Они только раздувают файл и заставляют скролить до них

2022-01-28 04:41 UTC, anaym commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            if (lastProtocol == null)
forceFull означает "не присылай мне патч"

2022-01-28 07:16 UTC, KungA commented on Vostok.ClusterConfig.Client/Updaters/ClusterConfigHeaderNames.cs
> +        public const string ReplicaName = "X-Kontur-ClusterConfig-Replica";
просто если эти константы ещё сервер использует, логичней в core положить

2022-01-28 07:21 UTC, KungA commented on Vostok.ClusterConfig.Client/Updaters/ClusterConfigHeaderNames.cs
> +        public const string ReplicaName = "X-Kontur-ClusterConfig-Replica";
аналогично с параметрами

2022-01-28 07:22 UTC, KungA commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            if (lastProtocol == null)
тогда давай вычислим forceFull снаружи и проверим потом что нам в ответ прислали не патч

2022-01-28 08:56 UTC, anaym commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            if (lastProtocol == null)
Ты имеешь ввиду снаружи метода CreateRequest?

2022-01-28 08:56 UTC, KungA commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            if (lastProtocol == null)
да, ну чтобы "и проверим потом что нам в ответ прислали не патч" смочь сделать

2022-01-28 11:41 UTC, KungA approved these changes

2022-01-28 11:41 UTC, KungA commented on Vostok.ClusterConfig.Client/Helpers/ApplyPatchHelper.cs
> +    public static byte[] ApplyV2Patch(this byte[] old, byte[] patch)
выглядит как экстеншен к TreeSerializerV2/IBinaryPatcher (а значит лучше его в core унести)

посмотри как у тебя целая зона десериализуется (через protocol.GetSerializer()), а тут получается ещё один сериализатор создаётся

лучше один и тот же использовать

2022-01-28 11:41 UTC, KungA commented on Vostok.ClusterConfig.Client/ProtocolVersion.cs
> +        [Obsolete("Use V2 instead")]
весь солюшен теперь в ворнингах

и протокол в2 пока не обкатан

поэтому предлагаю пока Obsolete убрать

2022-01-28 11:41 UTC, KungA commented on Vostok.ClusterConfig.Client/ProtocolVersion.cs
> +    public enum ProtocolVersion
Слишком общее название для корнегого неймспейса

Либо унеси в папку (Configuration), либо переназови с префиксом ClusterConfig

2022-02-01 07:37 UTC, KungA commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            if (!EnsureHashValid(tree.Serialized, response, version, false))
а тут зачем проверять, нам же всю зону прислали?

2022-02-01 07:40 UTC, KungA commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            log.Error($"Detected hash mismatch: {hash} != {expectedHash}. New version is {newVersion}, is patch: {isPatch}.");
это не структурированное логирование

2022-02-01 07:47 UTC, KungA commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            var newZone = protocol.GetPatcher().ApplyPatch(lastResult.Tree.Serialized, patch);
если у нас тут разъехались данные и вылетел эксепшен, то мы никогда не посчитаем хэш чтобы понять что данные пора выкидывать

2022-02-01 07:49 UTC, KungA commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            if (!EnsureHashValid(tree.Serialized, response, version, false))
и поэтому я бы ещё поменял HashMismatch на ForceFull

2022-02-01 07:50 UTC, KungA commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            var newZone = protocol.GetPatcher().ApplyPatch(lastResult.Tree.Serialized, patch);
и поэтому я бы ещё поменял RemoteUpdateResult.HashMismatch на ForceFull

2022-02-01 07:53 UTC, KungA commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            if (lastVersion.HasValue && !hashMismatch)
не понятно зачем это ( && !hashMismatch), мы же всё равно forceFull заполняем

2022-02-01 08:41 UTC, anaym commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            if (!EnsureHashValid(tree.Serialized, response, version, false))
Для единообразия решил добавить. Это такая проблема?

2022-02-01 08:42 UTC, KungA commented on Vostok.ClusterConfig.Client/Updaters/RemoteUpdater.cs
> +            if (!EnsureHashValid(tree.Serialized, response, version, false))
я бы оставил лог если хочется, но даже если не совпал хэш обновлял настройки итоговые

2022-02-01 09:24 UTC, KungA approved these changes

2022-02-02 08:49 UTC, KungA commented on Vostok.ClusterConfig.Client.Tests/Functional/FunctionalTests.cs
> +            if (protocol != ClusterConfigProtocolVersion.V2)
эти штуки делают кучу ворнинг-аннотаций

https://github.com/vostok/clusterconfig.client/actions/runs/1782375478

лучше просто return написать (или найти другой способ)

![image](https://user-images.githubusercontent.com/6822967/152121701-21d0e724-2951-4891-b7ac-3491fbe84d99.png)

2022-02-02 08:50 UTC, KungA approved these changes

2022-02-03 09:48 UTC, merged